- name: netology-ml
  hosts: all
  become: yes

  vars:
    packages:
      - net-tools
      - git
      - tree
      - htop
      - mc
      - vim

  tasks:
    - name: Task Ping
      ping:

    - name: Update Apt
      apt:
        update_cache: yes

    - name: Install Packages
      apt:
        name: "{{packages}}"
        state: latest

    - name: Copy File
      copy:
        src: test.txt
        dest: /home/ansible/test.txt
        mode: 0777

    - name: Create Group
      group:
        name: "{{item}}"
        state: present
      loop:
        - devops_1
        - test_1

    - name: Create Users
      user:
        name: "{{item.user_name}}"
        shell: /bin/bash
        groups: devops_1, test_1
        home: "/home/{{item.home_dir}}"
      with_items:
        - {user_name: devops_1, home_dir: devops_1}
        - {user_name: test_1, home_dir: test_1}