apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-ml
  namespace: default
  labels:
    app: tomcat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat-app
  template:
    metadata:
      labels:
        app: tomcat-app
    spec:
      containers:
        - name: tomcat
          image: tomcat:8.5.69 
          ports:
            - containerPort: 8080
      restartPolicy: Always
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
